### ISSUE TITLE
404 from localized pages

### ISSUE THREAD

**Issue by Manaus** [DeuxHuitHuit/page_lhandles#31]
Hello,
I compiled the pages handles for the three languages (it,en,fr), but when I try to load a page `http://localhost/website/it/home` with a lhandle, example is `http://localhost/website/fr/accueil/`, `http://localhost/website/en/homepage/` I get a 404.
It works though if I load `http://localhost/website/en/home/`or `http://localhost/website/fr/home/`
The app seems to render pages which are requested through the general (not localised) url handle. 

This is the .htaccess hunk: 

```
### LANGUAGE REDIRECT RULES start
RewriteCond %{REQUEST_FILENAME} !-d
RewriteCond %{REQUEST_FILENAME} !-f
RewriteRule ^(it|en|fr)-?()?\/(.*\/?)$ index.php?language=$1&region=$2&symphony-page=$3&%{QUERY_STRING} [L]
### LANGUAGE REDIRECT RULES end
```

I'm using Flang Detection 1.1, Sym 2.3.4, Page LHandles 2.9, Frontend Localisation 1.7.1, Languages 1.2  

Thanks

**Comment by nitriques** [comment]
Can you find the line in your .htaccess where you have a beginning with `RewriteBase` ?

Can you also show me the regular symphony rewrite please ? thanks!

**Comment by nitriques** [comment]
Ping @Manaus !

**Comment by nitriques** [comment]
Closing as no feedback in 6 weeks. Please re-open or comment as needed.
