### ISSUE TITLE
Not PHP 7 compatible

### ISSUE THREAD

**Issue by wdebusschere** [DeuxHuitHuit/page_lhandles#32]
Symphony Warning: Declaration of Extension_page_lhandles::update($previous_version) should be compatible with Extension::update($previousVersion = false)

**Comment by wdebusschere** [comment]
Fix from @animaux

change
public function update($previous_version){
to
public function update($previous_version = false){

**Comment by animaux** [comment]
Thanks. No need to credit me `:)` the error message does all the guidance.

**Comment by wdebusschere** [comment]
Another error appears: 
Symphony Warning: Declaration of MultilingualNavigationDatasource::__buildPageXML($page, $page_types, $qf) should be compatible with NavigationDatasource::__buildPageXML($page, $page_types)

An error occurred in /Users/xxx/Sites/framework/extensions/page_lhandles/lib/class.datasource.MultilingualNavigation.php around line 8
