### ISSUE TITLE
Not PHP 7.0 compatible: Symphony Warning: Declaration of MultilingualNavigationDatasource::__buildPageXML($page, $page_types, $qf)

### ISSUE THREAD

**Issue by wdebusschere** [DeuxHuitHuit/page_lhandles#33]
Error:
Symphony Warning: Declaration of MultilingualNavigationDatasource::__buildPageXML($page, $page_types, $qf) should be compatible with NavigationDatasource::__buildPageXML($page, $page_types)

An error occurred in /Users/xxx/Sites/framework/extensions/page_lhandles/lib/class.datasource.MultilingualNavigation.php around line 8

**Comment by nitriques** [comment]
This will be hard to fix, sadly. It will require a modification in the core.

**Comment by wdebusschere** [comment]
Its a modification in the core an option? I guess lots of people are using this extension.. Thank you.

**Comment by nitriques** [comment]
I though we needed a modification in the core to add the extra parameter. But turns out, we are lucky enough to not require this, since the base class does not call our function.

**Comment by wdebusschere** [comment]
Nitriques, after updating i get:

```
Symphony Warning: Declaration of MultilingualNavigationDatasource::execute(&$param_pool) should be compatible with NavigationDatasource::execute(?array &$param_pool = NULL)
An error occurred in /Users/xxx/Sites/framework/extensions/page_lhandles/lib/class.datasource.MultilingualNavigation.php around line 8
```

**Comment by nitriques** [comment]
`2.10.1` should fix that. Thanks!
