### ISSUE TITLE
PHP 7: Symphony Warning: Declaration of datasourceplh_page::grab(&$param_pool = NULL) should be compatible with Datasource::grab(?array &$param_pool = NULL)

### ISSUE THREAD

**Issue by wdebusschere** [DeuxHuitHuit/page_lhandles#34]
Symphony Warning: Declaration of datasourceplh_page::grab(&$param_pool = NULL) should be compatible with Datasource::grab(?array &$param_pool = NULL)
Line 24 in data.plh_page.php
`public function grab(&$param_pool = null) {`
to
`public function grab(array &$param_pool = null) {`

**Comment by nitriques** [comment]
Can you delete and recreate the DS? Are you running Symphony 2.7.0 ?

**Comment by wdebusschere** [comment]
i just updated the extensions, same error symphony 2.6.11

**Comment by wdebusschere** [comment]
got the same problem also with https://github.com/twiro/anti_spam_question/issues/4

**Comment by nitriques** [comment]
You might need to run Symphony 2.7.0 for PHP 7 support. I'll check this ASAP.
The grab function is deprecated: you can try to rename it to execute.

```php
public function execute(array &$param_pool = null)
```

**Comment by wdebusschere** [comment]
yes, that works

**Comment by nitriques** [comment]
Yeah I do not know how to handle this rename... Maybe I should try to add something in the README ?

**Comment by wdebusschere** [comment]
Does the extension copies the datasource from the extension to the workspace data-sources folder?

**Comment by nitriques** [comment]
Right now, we do not touch any data sources. Let me try some things.

**Comment by nitriques** [comment]
> Does the extension copies the datasource from the extension to the workspace data-sources folder?

Yes it does!

**Comment by nitriques** [comment]
@wdebusschere wanna try to upgrade to `2.11.0` please ? Thanks!

**Comment by nitriques** [comment]
> Does the extension copies the datasource from the extension to the workspace data-sources folder?

Finally, no it does not!!! It has a `PHL: Page` DS which is extension provided, and also patches and DS that has 'navigation' as it source. ouf!

**Comment by nitriques** [comment]
This was the real fix: https://github.com/DeuxHuitHuit/page_lhandles/commit/b0405548b849712459153eeaeadf16500bec425c

But I've fixed the nav DS customization as well!

**Comment by wdebusschere** [comment]
With 2.11.0 our Localised URL Handle don't work anymore..

**Comment by nitriques** [comment]
Yeah it was to late to do a release. Check out the fix: 19e087a

Released as `2.11.1`. Thanks.

**Comment by wdebusschere** [comment]
Works! Thanks
